###############################################################################
# Created by write_sdc
# Fri Sep 22 20:38:22 2023
###############################################################################
current_design user_proj_IMPACT_HEAD
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 25.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[10]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[11]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[12]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[13]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[14]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[15]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[16]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[17]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[18]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[19]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[20]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[21]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[22]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[23]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[24]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[25]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[26]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[27]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[28]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[29]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[30]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[31]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[5]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[6]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[7]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[8]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {East[9]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[10]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[11]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[12]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[13]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[14]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[15]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[16]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[17]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[18]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[19]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[20]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[21]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[22]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[23]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[24]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[25]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[26]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[27]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[28]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[29]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[30]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[31]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[5]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[6]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[7]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[8]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[9]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[0]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[10]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[11]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[12]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[13]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[14]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[15]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[16]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[17]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[18]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[19]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[1]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[20]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[21]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[22]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[23]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[24]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[25]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[26]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[27]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[28]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[29]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[2]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[30]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[31]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[3]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[4]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[5]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[6]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[7]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[8]}]
set_input_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[9]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[0]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[10]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[11]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[12]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[13]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[14]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[15]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[16]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[17]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[18]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[19]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[1]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[20]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[21]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[22]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[23]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[24]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[25]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[26]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[27]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[28]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[29]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[2]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[30]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[31]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[3]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[4]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[5]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[6]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[7]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[8]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {South[9]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[0]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[10]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[11]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[12]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[13]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[14]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[15]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[16]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[17]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[18]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[19]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[1]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[20]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[21]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[22]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[23]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[24]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[25]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[26]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[27]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[28]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[29]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[2]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[30]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[31]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[3]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[4]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[5]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[6]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[7]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[8]}]
set_output_delay 5.0000 -clock [get_clocks {clk}] -add_delay [get_ports {West[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {South[31]}]
set_load -pin_load 0.0334 [get_ports {South[30]}]
set_load -pin_load 0.0334 [get_ports {South[29]}]
set_load -pin_load 0.0334 [get_ports {South[28]}]
set_load -pin_load 0.0334 [get_ports {South[27]}]
set_load -pin_load 0.0334 [get_ports {South[26]}]
set_load -pin_load 0.0334 [get_ports {South[25]}]
set_load -pin_load 0.0334 [get_ports {South[24]}]
set_load -pin_load 0.0334 [get_ports {South[23]}]
set_load -pin_load 0.0334 [get_ports {South[22]}]
set_load -pin_load 0.0334 [get_ports {South[21]}]
set_load -pin_load 0.0334 [get_ports {South[20]}]
set_load -pin_load 0.0334 [get_ports {South[19]}]
set_load -pin_load 0.0334 [get_ports {South[18]}]
set_load -pin_load 0.0334 [get_ports {South[17]}]
set_load -pin_load 0.0334 [get_ports {South[16]}]
set_load -pin_load 0.0334 [get_ports {South[15]}]
set_load -pin_load 0.0334 [get_ports {South[14]}]
set_load -pin_load 0.0334 [get_ports {South[13]}]
set_load -pin_load 0.0334 [get_ports {South[12]}]
set_load -pin_load 0.0334 [get_ports {South[11]}]
set_load -pin_load 0.0334 [get_ports {South[10]}]
set_load -pin_load 0.0334 [get_ports {South[9]}]
set_load -pin_load 0.0334 [get_ports {South[8]}]
set_load -pin_load 0.0334 [get_ports {South[7]}]
set_load -pin_load 0.0334 [get_ports {South[6]}]
set_load -pin_load 0.0334 [get_ports {South[5]}]
set_load -pin_load 0.0334 [get_ports {South[4]}]
set_load -pin_load 0.0334 [get_ports {South[3]}]
set_load -pin_load 0.0334 [get_ports {South[2]}]
set_load -pin_load 0.0334 [get_ports {South[1]}]
set_load -pin_load 0.0334 [get_ports {South[0]}]
set_load -pin_load 0.0334 [get_ports {West[31]}]
set_load -pin_load 0.0334 [get_ports {West[30]}]
set_load -pin_load 0.0334 [get_ports {West[29]}]
set_load -pin_load 0.0334 [get_ports {West[28]}]
set_load -pin_load 0.0334 [get_ports {West[27]}]
set_load -pin_load 0.0334 [get_ports {West[26]}]
set_load -pin_load 0.0334 [get_ports {West[25]}]
set_load -pin_load 0.0334 [get_ports {West[24]}]
set_load -pin_load 0.0334 [get_ports {West[23]}]
set_load -pin_load 0.0334 [get_ports {West[22]}]
set_load -pin_load 0.0334 [get_ports {West[21]}]
set_load -pin_load 0.0334 [get_ports {West[20]}]
set_load -pin_load 0.0334 [get_ports {West[19]}]
set_load -pin_load 0.0334 [get_ports {West[18]}]
set_load -pin_load 0.0334 [get_ports {West[17]}]
set_load -pin_load 0.0334 [get_ports {West[16]}]
set_load -pin_load 0.0334 [get_ports {West[15]}]
set_load -pin_load 0.0334 [get_ports {West[14]}]
set_load -pin_load 0.0334 [get_ports {West[13]}]
set_load -pin_load 0.0334 [get_ports {West[12]}]
set_load -pin_load 0.0334 [get_ports {West[11]}]
set_load -pin_load 0.0334 [get_ports {West[10]}]
set_load -pin_load 0.0334 [get_ports {West[9]}]
set_load -pin_load 0.0334 [get_ports {West[8]}]
set_load -pin_load 0.0334 [get_ports {West[7]}]
set_load -pin_load 0.0334 [get_ports {West[6]}]
set_load -pin_load 0.0334 [get_ports {West[5]}]
set_load -pin_load 0.0334 [get_ports {West[4]}]
set_load -pin_load 0.0334 [get_ports {West[3]}]
set_load -pin_load 0.0334 [get_ports {West[2]}]
set_load -pin_load 0.0334 [get_ports {West[1]}]
set_load -pin_load 0.0334 [get_ports {West[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {East[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {South[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {West[0]}]
set_timing_derate -early 0.9500
set_timing_derate -late 1.0500
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_fanout 10.0000 [current_design]
